# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2026-06-03T05:32:40+00:00

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field


class UnMarkProcedureAsCancellingCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')


class RollbackCompleteProcedureCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    updated: AwareDatetime


class RollbackCancelProcedureCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    updated: AwareDatetime


class PlanProcedureCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    planningDate: AwareDatetime = Field(
        ..., description='Дата и время планируемого выполнения процедуры'
    )
    dayTimePeriod: str | None = Field(
        None, description='Период выполнения (ночь/утро/день/вечер)'
    )
    procedureDressing: str | None = Field(None, description='Посев')
    isDoctor: bool | None = Field(False, description='Требуется присутствие врача')
    room: str | None = Field(None, description='Кабинет')
    deviceId: str | None = Field(None, description='Аппарат для проведения')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    cito: Literal['CITO', 'PLANNED', 'EMERGENT'] | None = Field(
        None, description='Срочность'
    )
    updated: AwareDatetime = Field(..., description='Дата обновления')


class ChangeDoctor(BaseModel):
    workplaceId: str | None = None
    doctorName: str | None = None
    doctorJobTitle: str | None = None


class ProcedureStatusHistory(BaseModel):
    status: Literal[
        'PLANNED',
        'CANCELLING',
        'CANCELLED',
        'COMPLETED',
        'NOT_COMPLETED',
        'COMPLETED_PROTOCOL',
        'STARTED',
        'STARTED_PROTOCOL',
    ]
    updated: AwareDatetime
    workplaceId: str | None = None
    doctorName: str | None = None
    doctorJobTitle: str | None = None


class StatusHistory(BaseModel):
    status: Literal[
        'CREATED',
        'ACTIVE',
        'ASSIGNED',
        'EDITING',
        'CANCELLING',
        'CANCELLED',
        'READY_TO_DESCRIBE',
        'DONE',
        'FINISHING',
        'COMPLETED',
        'NOT_COMPLETED',
        'DELETED',
        'DESCRIBING',
    ]
    updated: AwareDatetime
    sortOrder: int
    workplaceId: str | None = None
    doctorName: str | None = None
    doctorJobTitle: str | None = None


class MarkProcedureDressingCommand(BaseModel):
    assignmentCompositionUid: str
    code: str
    updated: AwareDatetime
    procedureDressing: str
    workplaceId: str | None = None
    doctorName: str | None = None
    doctorJob: str | None = None


class MarkProcedureAsCancellingCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    byExecutor: bool


class Sorting(BaseModel):
    """
    Параметры сортировки доступные по логической модели направлений
    """

    field: str
    direction: Literal['asc', 'desc']


class DeactivateProcedureCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    updated: AwareDatetime


class CompleteWithProtocolProcedureCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    resultCompositionUid: str = Field(
        ...,
        description='Идентификатор композиции закрывающего процедуру из назначения документа',
    )
    description: str
    procedureDressing: str | None = None
    updated: AwareDatetime


class CompleteProcedureCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    resultCompositionUid: str
    description: str | None = None
    procedureDressing: str | None = None
    updated: AwareDatetime


class TimeCommitted(BaseModel):
    value: AwareDatetime | None = None


class CancelProcedureCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    byExecutor: bool | None = None
    resultCompositionUid: str
    updated: AwareDatetime


class ActivateWithProtocolProcedureCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    updated: AwareDatetime


class ActivateProcedureCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    code: str = Field(..., description='Идентификатор процедуры')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    updated: AwareDatetime


class ScheduleItem(BaseModel):
    """
    Массив, схема выполнения процедур
    """

    code: str
    planningDate: AwareDatetime
    periodCode: str | None = None
    procedureDressing: str | None = None
    isDoctor: bool | None = Field(False, description='Требуется присутствие врача')
    room: str | None = Field(None, description='Кабинет')
    deviceId: str | None = Field(None, description='Аппарат для проведения')


class UnMarkProcedureAssignmentAsFinishingCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    updated: AwareDatetime = Field(..., description='Время обновления')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')


class UnMarkProcedureAssignmentAsCancellingCommand(BaseModel):
    assignmentCompositionUid: str
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')


class RollbackCompleteProcedureAssignmentCommand(BaseModel):
    assignmentCompositionUid: str
    updated: AwareDatetime
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')


class RollbackCancelProcedureAssignmentCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    updated: AwareDatetime = Field(..., description='Дата и время обновления события')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')


class PlanProcedureAssignmentCommand(BaseModel):
    ehrId: str = Field(..., description='Идентификатор карты')
    patientId: str = Field(..., description='Идентификатор пациента')
    careCaseId: UUID = Field(..., description='Идентификатор обращения пациента')
    assignmentCompositionUid: str = Field(..., description='Идентификатор композиции')
    assignmentCode: str = Field(..., description='Код исследования')
    assignmentName: str = Field(..., description='Наименование исследования')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО назначившего врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    assigneeId: int | None = Field(None, description='Назначенный специалист')
    assigneeName: str | None = Field(None, description='ФИО назначенного специалиста')
    cito: Literal['CITO', 'PLANNED', 'EMERGENT'] | None = Field(
        None, description='Срочность'
    )
    assignmentDate: AwareDatetime | None = Field(
        None,
        description='Дата выполнения назначения (на какую дату назначена процедура или с какой даты необходимо начало выполнения курса процедур)',
    )
    updated: AwareDatetime = Field(..., description='Дата и время обновления события')
    created: AwareDatetime
    effectArea: str | None = Field(None, description='Область воздействия')
    schedule: list[ScheduleItem] | None = Field(
        None, description='Массив, схема выполнения процедур'
    )
    procedureCount: int | None = Field(
        None, description='Количество процедур в назначении'
    )


class MarkProcedureAssignmentAsFinishingCommand(BaseModel):
    resultCompositionUid: str | None = Field(
        None, description='Идентификатор композиции результирующего документа'
    )
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    updated: AwareDatetime = Field(..., description='Время обновления')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО назначившего врача')
    doctorJob: str | None = Field(
        None, description='Должность взявшего в работу Специалиста'
    )


class MarkProcedureAssignmentAsEditingCommand(BaseModel):
    assignmentCompositionUid: str
    updated: AwareDatetime
    workplaceId: str
    doctorName: str | None = None
    doctorJob: str | None = None


class MarkProcedureAssignmentAsCancellingCommand(BaseModel):
    assignmentCompositionUid: str
    byExecutor: bool | None = None
    workplaceId: str | None = None
    doctorName: str | None = None
    doctorJob: str | None = None


class GetProcedureAssignmentsQuery(BaseModel):
    careCaseId: UUID | None = None
    assignmentIds: list[UUID] | None = None
    assignmentCompositionUids: list[str] | None = None
    doctorId: str | None = None
    doctorName: str | None = None
    assigneeId: int | None = None
    executorId: int | None = None
    assignmentName: str | None = None
    dateFrom: AwareDatetime
    dateTo: AwareDatetime
    sorting: Sorting | None = None


class FindDuplicates(BaseModel):
    careCaseId: UUID = Field(..., description='Идентификатор обращения')
    assignmentCode: list[str] = Field(..., description='Коды исследований')
    statuses: (
        list[
            Literal[
                'CREATED',
                'ACTIVE',
                'ASSIGNED',
                'EDITING',
                'CANCELLING',
                'CANCELLED',
                'READY_TO_DESCRIBE',
                'DONE',
                'FINISHING',
                'COMPLETED',
                'NOT_COMPLETED',
                'DELETED',
                'DESCRIBING',
            ]
        ]
        | None
    ) = Field(None, description='Статусы по которым выполняется проверка дубликатов')
    period: int | None = Field(
        None, description='Период в днях за который выполняется поиск дуликатов'
    )


class AssignmentDuplicate(BaseModel):
    assignmentCode: str
    assignmentId: UUID | None = None
    status: (
        Literal[
            'CREATED',
            'ACTIVE',
            'ASSIGNED',
            'EDITING',
            'CANCELLING',
            'CANCELLED',
            'READY_TO_DESCRIBE',
            'DONE',
            'FINISHING',
            'COMPLETED',
            'NOT_COMPLETED',
            'DELETED',
            'DESCRIBING',
        ]
        | None
    ) = None


class GetProcedureAssignmentsBetweenQuery(BaseModel):
    patientId: str | None = None
    ehrId: str | None = None
    workplaceId: str | None = None
    dateFrom: AwareDatetime
    dateTo: AwareDatetime


class DoneProcedureAssignmentCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    updated: AwareDatetime = Field(..., description='Время обновления')
    byExecutor: bool | None = Field(
        None, description='Отмену вызвал исполнитель или инициатор'
    )
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')


class DeleteProcedureAssignmentCommand(BaseModel):
    assignmentCompositionUid: str
    updated: AwareDatetime
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')


class DeactivateProcedureAssignmentCommand(BaseModel):
    assignmentCompositionUid: str
    updated: AwareDatetime | None = None
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')


class CompleteProcedureAssignmentCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    resultCompositionUid: str = Field(
        ..., description='Идентификатор композиции закрывающего назначение документа'
    )
    updated: AwareDatetime = Field(..., description='Время обновления')
    completed: AwareDatetime = Field(..., description='Время выполнения')
    workplaceId: str | None = Field(
        None, description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(
        None, description='ФИО взявшего в работу специалиста'
    )
    doctorJob: str | None = Field(
        None, description='Должность взявшего в работу специалиста'
    )


class CancelProcedureAssignmentCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    resultCompositionUid: str = Field(
        ..., description='Идентификатор композиции документа отмены'
    )
    updated: AwareDatetime = Field(..., description='Дата и время обновления события')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')


class ActivateProcedureAssignmentCommand(BaseModel):
    assignmentCompositionUid: str = Field(
        ..., description='Идентификатор композиции назначения'
    )
    updated: AwareDatetime | None = Field(
        None, description='Время возникновения события или время взятия в работу'
    )
    byExecutor: bool | None = Field(
        None, description='Отмену вызвал исполнитель или инициатор'
    )
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str = Field(..., description='ФИО взявшего в работу специалиста')
    doctorJob: str | None = Field(
        None, description='Должность взявшего в работу специалиста'
    )


class ProcedureShortInfo(BaseModel):
    dayTimePeriod: str | None = None
    assignedByDate: bool | None = None
    status: Literal[
        'PLANNED',
        'CANCELLING',
        'CANCELLED',
        'COMPLETED',
        'NOT_COMPLETED',
        'COMPLETED_PROTOCOL',
        'STARTED',
        'STARTED_PROTOCOL',
    ]
    resultCompositionUid: str | None = None
    code: str
    executorId: int | None = None
    executorName: str | None = None
    executorJob: str | None = None
    byExecutor: bool | None = None
    cito: Literal['CITO', 'PLANNED', 'EMERGENT'] | None = None
    description: str | None = None
    procedureDressing: str | None = None
    isDoctor: bool | None = None
    room: str | None = None
    deviceId: str | None = None
    isChecked: bool | None = None
    planningDate: AwareDatetime | None = None
    completedDate: AwareDatetime | None = None
    cancelledDate: AwareDatetime | None = None
    created: AwareDatetime
    updated: AwareDatetime | None = None
    createdUserId: str
    updatedUserId: str
    tenantId: str
    statusHistory: list[ProcedureStatusHistory] | None = None
    changeDoctor: ChangeDoctor | None = None


class GetProceduresQuery(BaseModel):
    statuses: (
        list[
            Literal[
                'PLANNED',
                'CANCELLING',
                'CANCELLED',
                'COMPLETED',
                'NOT_COMPLETED',
                'COMPLETED_PROTOCOL',
                'STARTED',
                'STARTED_PROTOCOL',
            ]
        ]
        | None
    ) = Field(None, description='Статусы  процедур')
    careCaseId: list[UUID] | None = Field(
        None, description='Идентификатор обращения пациента'
    )
    patientId: list[str] | None = Field(None, description='Идентификатор пациент')
    ehrId: list[str] | None = Field(None, description='Идентификаторы карт')
    assignmentIds: list[UUID] | None = Field(
        None, description='Идентификаторы назначений'
    )
    assignmentCompositionUids: list[str] | None = Field(
        None, description='Идентификаторы композиций'
    )
    assignmentStatuses: (
        list[
            Literal[
                'CREATED',
                'ACTIVE',
                'ASSIGNED',
                'EDITING',
                'CANCELLING',
                'CANCELLED',
                'READY_TO_DESCRIBE',
                'DONE',
                'FINISHING',
                'COMPLETED',
                'NOT_COMPLETED',
                'DELETED',
                'DESCRIBING',
            ]
        ]
        | None
    ) = Field(None, description='Статусы назначений содержащих процедуры')
    assignmentName: str | None = Field(None, description='Наименование услуги')
    dayTimePeriod: list[str] | None = Field(None, description='Период выполнения')
    dateFrom: AwareDatetime = Field(
        ..., description='Отбор процедур по дате исполнения С'
    )
    dateTo: AwareDatetime = Field(
        ..., description='Отбор процедур по дате исполнения По'
    )
    sorting: Sorting | None = None


class ProcedureAssignmentInfo(BaseModel):
    id: UUID
    status: Literal[
        'CREATED',
        'ACTIVE',
        'ASSIGNED',
        'EDITING',
        'CANCELLING',
        'CANCELLED',
        'READY_TO_DESCRIBE',
        'DONE',
        'FINISHING',
        'COMPLETED',
        'NOT_COMPLETED',
        'DELETED',
        'DESCRIBING',
    ]
    patientId: str
    ehrId: str
    careCaseId: UUID
    assignmentCompositionUid: str
    assignmentCode: str
    assignmentName: str
    draftUid: str | None = None
    resultCompositionUid: str | None = None
    assigneeId: int | None = None
    assigneeName: str | None = None
    byExecutor: bool | None = None
    cito: Literal['CITO', 'PLANNED', 'EMERGENT'] | None = None
    assignmentDate: AwareDatetime | None = None
    signDate: AwareDatetime | None = None
    completedDate: AwareDatetime | None = None
    workplaceId: str
    doctorName: str | None = None
    doctorJob: str | None = None
    created: AwareDatetime
    updated: AwareDatetime | None = None
    statusHistory: list[StatusHistory] | None = None
    effectArea: str | None = None
    pmuNaz: str | None = None
    procedureCount: int | None = None
    procedures: list[ProcedureShortInfo] | None = None


class AuditDetails(BaseModel):
    time_committed: TimeCommitted | None = None


class CreateProcedureAssignmentCommand(BaseModel):
    ehrId: str = Field(..., description='Идентификатор карты')
    patientId: str = Field(..., description='Идентификатор пациента')
    careCaseId: UUID = Field(..., description='Идентификатор обращения пациента')
    assignmentCompositionUid: str = Field(..., description='Идентификатор композиции')
    assignmentCode: str = Field(..., description='Код исследования')
    assignmentName: str = Field(..., description='Наименование исследования')
    workplaceId: str = Field(
        ..., description='Идентификатор рабочего места взявшего в работу специалиста'
    )
    doctorName: str | None = Field(None, description='ФИО назначившего врача')
    doctorJob: str | None = Field(None, description='Наименование должности врача')
    assigneeId: int | None = Field(None, description='Назначенный специалист')
    assigneeName: str | None = Field(None, description='ФИО назначенного специалиста')
    cito: Literal['CITO', 'PLANNED', 'EMERGENT'] | None = Field(
        None, description='Срочность'
    )
    assignmentDate: AwareDatetime | None = Field(
        None,
        description='Дата выполнения назначения (на какую дату назначена процедура или с какой даты необходимо начало выполнения курса процедур)',
    )
    updated: AwareDatetime = Field(..., description='Дата и время обновления события')
    created: AwareDatetime
    effectArea: str | None = Field(None, description='Область воздействия')
    schedule: list[ScheduleItem] | None = Field(
        None, description='Массив, схема выполнения процедур'
    )
    procedureCount: int | None = Field(
        None, description='Количество процедур в назначении'
    )
    pmuNaz: str = Field(..., description='Услуга ПМУ')


class AssignmentShortInfo(BaseModel):
    id: UUID
    status: Literal[
        'CREATED',
        'ACTIVE',
        'ASSIGNED',
        'EDITING',
        'CANCELLING',
        'CANCELLED',
        'READY_TO_DESCRIBE',
        'DONE',
        'FINISHING',
        'COMPLETED',
        'NOT_COMPLETED',
        'DELETED',
        'DESCRIBING',
    ]
    patientId: str
    ehrId: str
    careCaseId: UUID
    assignmentCompositionUid: str
    assignmentCode: str
    assignmentName: str
    draftUid: str | None = None
    resultCompositionUid: str | None = None
    assigneeId: int | None = None
    assigneeName: str | None = None
    byExecutor: bool | None = None
    cito: Literal['CITO', 'PLANNED', 'EMERGENT'] | None = None
    assignmentDate: AwareDatetime | None = None
    signDate: AwareDatetime | None = None
    completedDate: AwareDatetime | None = None
    workplaceId: str
    doctorName: str | None = None
    doctorJob: str | None = None
    created: AwareDatetime
    updated: AwareDatetime | None = None
    statusHistory: list[StatusHistory] | None = None
    effectArea: str | None = None
    pmuNaz: str | None = None
    procedureCount: int | None = None
    procedures: list[ProcedureShortInfo] | None = None


class ProcedureInfo(BaseModel):
    careCaseId: UUID
    dayTimePeriod: str | None = None
    assignedByDate: bool | None = None
    status: Literal[
        'PLANNED',
        'CANCELLING',
        'CANCELLED',
        'COMPLETED',
        'NOT_COMPLETED',
        'COMPLETED_PROTOCOL',
        'STARTED',
        'STARTED_PROTOCOL',
    ]
    assignmentCompositionUid: str
    resultCompositionUid: str | None = None
    code: str
    executorId: int | None = None
    executorName: str | None = None
    executorJob: str | None = None
    byExecutor: bool | None = None
    cito: Literal['CITO', 'PLANNED', 'EMERGENT'] | None = None
    description: str | None = None
    procedureDressing: str | None = None
    isDoctor: bool | None = None
    room: str | None = None
    deviceId: str | None = None
    isChecked: bool | None = None
    planningDate: AwareDatetime | None = None
    completedDate: AwareDatetime | None = None
    cancelledDate: AwareDatetime | None = None
    created: AwareDatetime
    updated: AwareDatetime | None = None
    assignment: AssignmentShortInfo | None = None
    createdUserId: str
    updatedUserId: str
    tenantId: str
    statusHistory: list[ProcedureStatusHistory] | None = None
    changeDoctor: ChangeDoctor | None = None


class AbstractProcedureAssignmentEvent(BaseModel):
    procedureAssignment: ProcedureAssignmentInfo | None = None
    changeDoctor: ChangeDoctor | None = None
    tenantId: str | None = None
    userId: str | None = None
    type: str


class ProcedureAssignmentActiveEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentAssignedEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentCanceledEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentCancellingEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentCompletedEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentCreatedEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentDeletedEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentDoneEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentEditingEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentMarkedAsFinishingEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureAssignmentUpdatedEvent(AbstractProcedureAssignmentEvent):
    pass


class ProcedureActionDocument(AbstractProcedureAssignmentEvent):
    code: str | None = None
    assignmentCompositionUid: str
    resultCompositionUid: str
    description: str | None = None
    planningDate: AwareDatetime
    currentState: str
    careflowCode: str | None = None
    workplaceId: str | None = None
    executorName: str | None = None
    executorJob: str | None = None
    userId: str | None = None
    tenantId: str
    profileId: int | None = None
    lifecycleState: Any
    updated: Any


class ProcedureAssignmentActionDocument(AbstractProcedureAssignmentEvent):
    completed: AwareDatetime
    assignmentCompositionUid: str
    resultCompositionUid: str
    currentState: str
    careflowCode: str | None = None
    workplaceId: str | None = None
    executorName: str | None = None
    executorJob: str | None = None
    userId: str | None = None
    tenantId: str
    profileId: int | None = None
    lifecycleState: Any
    updated: Any


class ProcedureAssignmentCancellationActionDocument(AbstractProcedureAssignmentEvent):
    assignmentCompositionUid: str
    currentState: str
    careflowCode: str | None = None
    code: str | None = None
    doctorId: str
    doctorName: str | None = None
    doctorJob: str | None = None
    resultCompositionUid: str | None = None
    userId: str | None = None
    tenantId: str
    profileId: int | None = None
    lifecycleState: Any
    updated: Any


class ProcedureAssignmentInstructionDocument(AbstractProcedureAssignmentEvent):
    created: AwareDatetime
    ehrId: str
    patientId: str
    careCaseId: UUID
    assignmentCompositionUid: str
    assignmentCode: str
    assignmentName: str
    assignmentDate: AwareDatetime | None = None
    assigneeId: int | None = None
    assigneeName: str | None = None
    doctorId: str
    doctorName: str | None = None
    doctorJob: str | None = None
    cito: Literal['CITO', 'PLANNED', 'EMERGENT']
    effectArea: str | None = None
    schedule: str | None = None
    procedureCount: int | None = None
    userId: str | None = None
    tenantId: str
    profileId: int | None = None
    lifecycleState: Any
    updated: Any


class EhrdbProcedureAssignmentDocumentPayload(BaseModel):
    """
    Атрибуты события
    """

    ehrUid: str | None = None
    operationType: Literal['create', 'update', 'delete'] | None = None
    eventName: str | None = None
    oldResults: (
        list[
            ProcedureActionDocument
            | ProcedureAssignmentActionDocument
            | ProcedureAssignmentCancellationActionDocument
            | ProcedureAssignmentInstructionDocument
        ]
        | None
    ) = None
    newResults: (
        list[
            ProcedureActionDocument
            | ProcedureAssignmentActionDocument
            | ProcedureAssignmentCancellationActionDocument
            | ProcedureAssignmentInstructionDocument
        ]
        | None
    ) = None
    auditDetails: AuditDetails | None = None
    compositionId: str | None = None


# ---------------------------------------------------------------------------
# Модели интеграционного сервиса (FastAPI Integration Service)
# ---------------------------------------------------------------------------

from typing import Any as _Any, Dict as _Dict, Optional as _Optional

from pydantic import ConfigDict


class ExecuteRequest(BaseModel):
    command_name: str
    tenant_id: str
    user_id: str
    override_payload: _Optional[_Dict[str, _Any]] = None

    model_config = ConfigDict(from_attributes=True)


class ExecuteResponse(BaseModel):
    status_code: int
    response: _Any
    request_payload: _Optional[_Any] = None
    error: _Optional[str] = None


class ExportRequest(BaseModel):
    export_index_final: bool = True


class TemplateBase(BaseModel):
    name: str
    method: str
    path: str
    payload: _Dict[str, _Any]


class TemplateResponse(TemplateBase):
    id: int


COMMAND_MODEL_BY_NAME: dict[str, type[BaseModel]] = {
    "Отменить отметку о процедуре (unmarkProcedureCancelling)": UnMarkProcedureAsCancellingCommand,
    "Откатить завершённую процедуру (rollbackCompleteProcedure)": RollbackCompleteProcedureCommand,
    "Откатить отмену процедуры (rollbackCancelProcedure)": RollbackCancelProcedureCommand,
    "Запланировать процедуру (planProcedure)": PlanProcedureCommand,
    "Отметить процедуру как отменяемую (markProcedureCancelling)": MarkProcedureAsCancellingCommand,
    "Получить список процедур (getProcedures)": GetProceduresQuery,
    "Деактивировать процедуру (deactivateProcedure)": DeactivateProcedureCommand,
    "Завершить процедуру с протоколом (completeWithProtocolProcedure)": CompleteWithProtocolProcedureCommand,
    "Завершить процедуру (completeProcedure)": CompleteProcedureCommand,
    "Отменить процедуру (cancelProcedure)": CancelProcedureCommand,
    "Активировать процедуру с протоколом (activateWithProtocolProcedure)": ActivateWithProtocolProcedureCommand,
    "Активировать процедуру (activateProcedure)": ActivateProcedureCommand,
    "Создать назначение (assignment)": CreateProcedureAssignmentCommand,
    "Снять отметку о завершении назначения (unmarkProcedureAssignmentAsFinishing)": UnMarkProcedureAssignmentAsFinishingCommand,
    "Снять отметку об отмене назначения (unmarkAssignmentAsCancelling)": UnMarkProcedureAssignmentAsCancellingCommand,
    "Откатить завершение назначения (rollbackComplete)": RollbackCompleteProcedureAssignmentCommand,
    "Откатить отмену назначения (rollbackCancelProcedureAssignment)": RollbackCancelProcedureAssignmentCommand,
    "Запланировать назначение (plan) - полный": PlanProcedureAssignmentCommand,
    "Планирование назначения (plan) с результатом": MarkProcedureAssignmentAsFinishingCommand,
    "Отметить назначение как редактируемое (markAssignmentAsEditing)": MarkProcedureAssignmentAsEditingCommand,
    "Отметить назначение как отменяемое (markAssignmentAsCancelling)": MarkProcedureAssignmentAsCancellingCommand,
    "Найти назначения (find)": GetProcedureAssignmentsQuery,
    "Найти дубликаты назначений (findDuplicates)": FindDuplicates,
    "Найти назначения между датами (findBetween)": GetProcedureAssignmentsBetweenQuery,
    "Отметить назначение как выполненное (doneProcedureAssignment)": DoneProcedureAssignmentCommand,
    "Удалить назначение (delete)": DeleteProcedureAssignmentCommand,
    "Деактивировать назначение (deactivateProcedureAssignment)": DeactivateProcedureAssignmentCommand,
    "Завершить назначение процедуры (completeProcedureAssignment)": CompleteProcedureAssignmentCommand,
    "Активировать назначение процедуры (activateProcedureAssignment)": ActivateProcedureAssignmentCommand,
}


def get_command_model(command_name: str) -> type[BaseModel] | None:
    return COMMAND_MODEL_BY_NAME.get(command_name)


def validate_command_payload(command_name: str, payload: dict[str, _Any]) -> dict[str, _Any]:
    """Валидирует payload по swagger-модели команды; возвращает сериализуемый dict."""
    model_cls = get_command_model(command_name)
    if model_cls is None:
        return payload
    return model_cls.model_validate(payload).model_dump(mode="json")
